version: "3"

services:
  naive-proxy:
    image: crapthings/naive-proxy
    container_name: naive-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/caddy/
      - ./logs:/var/log/caddy/
    restart: always
